name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, reopened]

jobs:
  unit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          python -m pip install invoke .[test]
          pip install flake8 pytest colorama pandas pyarrow exrex pytest-cov
    - name: Run unit tests
      run: |
        pytest --cov=sdgp --cov-report=xml tests/
    - if: matrix.os == 'ubuntu-latest' && matrix.python-version == 3.8
      name: Upload codecov report
      uses: codecov/codecov-action@v2
